---
- name: Install Server Density dependencies (Debian/Ubuntu)
  apt:
    name: curl
    state: present
  when: ansible_os_family == "Debian"

- name: Install Server Density dependencies (RedHat/CentOS)
  yum:
    name: curl
    state: present
  when: ansible_os_family == "RedHat"

- name: Install v2 Server Density agent
  include: agent.yml
  when: upgrade_v2 is not defined

- name: Upgrade Server Density agent to v2
  include: upgrade.yml
  when: upgrade_v2 is defined

- name: Copy config file
  template:
    src: config.template.j2
    dest: /etc/sd-agent/config.cfg
    owner: sd-agent
    group: sd-agent
    mode: 0660
    backup: yes
  notify: restart sd-agent

- name: Setup logrotate
  template:
    src: sd-logrotate.j2
    dest: /etc/logrotate.d/sd-logrotate
    owner: root
    group: root
    mode: 0644

- name: Install additional plugins
  include: plugins.yml
  when: plugins is defined

